name: aoc
version: 0.1.0

source-dirs: src

executable:
  main: Main.hs

ghc-options: -O2 -threaded

dependencies:
  - array
  - base
  - base16-bytestring
  - bytestring
  - cmdargs
  - containers
  - cryptohash-md5
  - heap
  - megaparsec
  - parallel
  - range
  - split
  - timeit
