name: aoc
version: 0.1.0

source-dirs: src

executable:
  main: Main.hs

dependencies:
  - array
  - base
  - base16-bytestring
  - bytestring
  - cmdargs
  - containers
  - cryptohash-md5
  - heap
  - megaparsec
  - split
